server:
  port: 8091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: demo-api-system
  datasource:
    hikari:
      jdbc-url: ENC(a2/7KzO7rtiiwSk7+6MnKL2nJ7dII6eUMm74u3CZOmHIGrk+W3vn7g6S1KK9dcWT)
      username: ENC(Uy6VEQdmCJb5oQS4xae+1g==)
      password: ENC(fsmPqw9GG8tXIkqmcCRosFR5fX9mo6bK)
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: 1q2w3e4r!


alis:
  package: com.demo.api.system
