server:
  port: 8091

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: demo-api-system
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/system
      username: root
      password: 9705dltka@L
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: 1q2w3e4r!

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

alis:
  package: com.demo.api.system
