server:
  port: 8082

spring:
  application:
    name: demo-web-backoffice
  redis:
    host: localhost
    port: 6379
    password: 1q2w3e4r!
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
