server:
  port: 8000

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: demo-api-system
          uri: lb://demo-api-system
          predicates:
            - Host=demo.shop.bo.com*
            - Path=/api/system/**
          filters:
            - RewritePath=/api/(?<path>.*),/$\{path}
            - AuthFilter
        - id: demo-api-system-fo
          uri: lb://demo-api-system
          predicates:
            - Path=/api/system/fo/**
          filters:
            - RewritePath=/api/(?<path>.*),/$\{path}
        - id: demo-web-backoffice-auth
          uri: lb://demo-web-backoffice
          predicates:
            - Host=demo.shop.bo.com*
            - Path=/web/bo/**
          filters:
            - RewritePath=/web/bo/(?<path>.*),/$\{path}
            - AuthFilter
        - id: demo-web-backoffice
          uri: lb://demo-web-backoffice
          predicates:
            - Host=demo.shop.bo.com*
            - Path=/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  auth:
    except-url-list: /system/login,/system/adminAuth